# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_entry_author_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_markdown.models.MarkdownField()),
            ],
        ),
    ]
