# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160430_0027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='entry',
            name='author_comment',
            field=django_markdown.models.MarkdownField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source_code',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
