# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160430_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetext',
            name='info',
            field=models.CharField(default='Text-2016-05-01 17:45:56.239947+00:00', max_length=140),
        ),
    ]
