# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_codetext_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetext',
            name='info',
            field=models.CharField(default='Text-2016-05-01 18:14:51.873436+00:00', max_length=140),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.Author'),
        ),
    ]
