# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160501_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetext',
            name='info',
            field=models.CharField(default='Text-2016-05-01 18:16:43.369226+00:00', max_length=140),
        ),
    ]
