# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160501_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.AlterField(
            model_name='codetext',
            name='info',
            field=models.CharField(default='Text-2016-05-01 18:22:06.082470+00:00', max_length=140),
        ),
    ]
