# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20160501_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ManyToManyField(related_name='author', to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='codetext',
            name='info',
            field=models.CharField(default='Text-2016-05-01 18:23:40.946207+00:00', max_length=140),
        ),
    ]
