# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160501_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetext',
            name='info',
            field=models.CharField(default='Text-2016-05-01 20:12:46.778893+00:00', max_length=140),
        ),
    ]
