# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:31
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20160501_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='body',
        ),
        migrations.AddField(
            model_name='entry',
            name='body',
            field=django_markdown.models.MarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CodeText',
        ),
    ]
